name: Test all

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  node:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: '15'
    - name: Install dependencies
      run: |
        npm install -g grunt-cli grunt yarn
        yarn

    - name: tests
      run: |
        grunt test
